Jake level design
SkeleKing042/ILOVEYOU-GAME pull request #168
Opened 2024-10-27 23:46 UTC by JakeClark-AIE

bring me back please

2024-10-28 00:32 UTC, SkeleKing042 approved these changes
👍

2024-11-05 23:22 UTC, SkeleKing042 requested changes

2024-11-05 23:22 UTC, SkeleKing042 commented on Assets/Art/Assets from Connor.meta
Is there a better name for this folder? Freelance Assets?

2024-11-05 23:24 UTC, JakeClark-AIE commented
yes, that's a better name for sure. feel free to change it

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Jackson Lucas ***@***.***>
Sent: Wednesday, November 6, 2024 9:52:55 AM
To: SkeleKing042/ILOVEYOU-GAME ***@***.***>
Cc: Jake Clark ***@***.***>; Author ***@***.***>
Subject: Re: [SkeleKing042/ILOVEYOU-GAME] Jake level design (PR #168)


@SkeleKing042 requested changes on this pull request.

________________________________

On Assets/Art/Assets from Connor.meta<https://github.com/SkeleKing042/ILOVEYOU-GAME/pull/168#discussion_r1830201852>:

Is there a better name for this folder? Freelance Assets?

—
Reply to this email directly, view it on GitHub<https://github.com/SkeleKing042/ILOVEYOU-GAME/pull/168#pullrequestreview-2416974272>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A6WKVEC6D5SE7NTBXT4WDXDZ7FHM7AVCNFSM6AAAAABQWJBYROVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMJWHE3TIMRXGI>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-11-08 03:10 UTC, SkeleKing042 approved these changes
👍

2024-11-10 22:51 UTC, merged